#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

branches:
  only:
    - master
    - develop

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# clone directory
clone_folder: C:\projects\ChocolateyGUI

# environment variables
environment:
  MyGetDevelopApiKey:
    secure: KFeZCL5TKhJaL96tl0H+HjcVYv/cSsVtFE48mYOpmCMuuNH/sId04odoavJqgl7f
  MyGetDevelopFeedUrl: https://www.myget.org/F/packages_develop
  MyGetMasterApiKey:
    secure: OewKlbHSmiVUj7kC0WMZwvjDQKBjcZNgSYyXIxDNGZxssxx4KDQNyRbT+6PZ+uPH
  MyGetMasterFeedUrl: https://www.myget.org/F/packages_master/
  ChocolateyApiKey:
    secure: rGZLB7/BIEUl7XMeMeidRD50lQe8igKyPUJSAzFBd146Foc67Vyagv1kJ4ImTGvY
  ChocolateyFeedUrl: https://chocolatey.org/
  GitHubUserName:
    secure: je/D8MZcaA0IMfIhmrqShQ==
  GitHubPassword:
    secure: DCLeGjj/fPf/rkF2y4e3ZEFta2Efnzof1GiOEIPdhw0PQs4NBnjaENwif1itJB96
   
#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - ps: .\BuildScripts\build.ps1
  
test: off

#---------------------------------#
#      caching configuration      #
#---------------------------------#

cache:
  - Source\packages

#---------------------------------#
#  notifications configuration    #
#---------------------------------#
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/4933c447ea42a0480587
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
